---
- name: Set gites_secret_key variables
  when: not gitea_secret_key
  block:
    - name: Check token file
      ansible.builtin.stat:
        path: "{{ gitea_work_dir }}/secret_key"
      register: token_file_stat_result
    - name: Get generated SECRET_KEY
      when: token_file_stat_result.stat.exists
      block:
        - name: Get generated SECRET_KEY
          ansible.builtin.command:
            cmd: cat {{ gitea_work_dir }}/secret_key
            removes: "{{ gitea_work_dir }}/secret_key"
          register: secret_key_result
          changed_when: false
        - name: Set SECRET_KEY variable
          ansible.builtin.set_fact:
            gitea_secret_key: "{{ secret_key_result.stdout }}"
    - name: Generate SECRET_KEY
      when: not token_file_stat_result.stat.exists
      block:
        - name: Generate SECRET_KEY
          ansible.builtin.command:
            cmd: "{{ gitea_install_dir }}/gitea generate secret SECRET_KEY"
            creates: "{{ gitea_work_dir }}/secret_key"
          register: secret_key_result
        - name: Set SECRET_KEY variable
          ansible.builtin.set_fact:
            gitea_secret_key: "{{ secret_key_result.stdout }}"
- name: Add/update generated token file
  ansible.builtin.template:
    src: token.j2
    dest: "{{ gitea_work_dir }}/secret_key"
    mode: "0644"
  vars:
    token_value: "{{ gitea_secret_key }}"
