---
- name: Setup database setting
  ansible.builtin.include_tasks: database/{{ gitea_cfg['database']['DB_TYPE'] }}.yml
  when: |
    gitea_cfg['database']['HOST'].startswith('localhost:')
    or
    gitea_cfg['database']['HOST'].startswith('127.0.0.1:')
- name: Execute database migration
  ansible.builtin.command:
    cmd: "{{ gitea_install_dir }}/gitea migrate -c {{ gitea_config_dir }}/app.ini"
    chdir: "{{ gitea_work_dir }}"
  become: true
  become_user: "{{ gitea_user }}"
  when: update_gitea is changed
