---
- name: install dependency packages
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
- name: Add gitea user
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    system: true
    comment: Git Version Control
    home: /home/{{ gitea_user }}
    password: "*"
- name: Create install directory
  ansible.builtin.file:
    path: "{{ gitea_home }}"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    state: directory
    mode: "0755"
- name: Create config directory
  ansible.builtin.file:
    path: "{{ gitea_config_dir }}"
    owner: root
    group: "{{ gitea_user }}"
    state: directory
    mode: "0770"
- name: Create working directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_user }}"
    state: directory
    mode: "750"
  loop:
    - "{{ gitea_working_dir }}"
    - "{{ gitea_working_dir }}/custom"
    - "{{ gitea_working_dir }}/data"
    - "{{ gitea_working_dir }}/log"
