---
- name: Check token file
  ansible.builtin.stat:
    path: "{{ gitea_work_dir }}/internal_token"
  register: token_file_stat_result
- name: Generate INTERNAL_TOKEN token
  when: not token_file_stat_result.stat.exists
  block:
    - name: Generate INTERNAL_TOKEN
      ansible.builtin.command:
        cmd: "{{ gitea_install_dir }}/gitea generate secret INTERNAL_TOKEN"
        creates: "{{ gitea_work_dir }}/internal_token"
      register: internal_token_result
    - name: Set INTERNAL_TOKEN variable
      ansible.builtin.set_fact:
        gitea_internal_token: "{{ internal_token_result.stdout }}"
- name: Get generated INTERNAL_TOKEN token
  when: token_file_stat_result.stat.exists
  block:
    - name: Get generated INTERNAL_TOKEN
      ansible.builtin.command:
        cmd: cat {{ gitea_work_dir }}/internal_token
        removes: "{{ gitea_work_dir }}/internal_token"
      register: internal_token_result
      changed_when: false
    - name: Set INTERNAL_TOKEN variable
      ansible.builtin.set_fact:
        gitea_internal_token: "{{ internal_token_result.stdout }}"
